application: simplewaf
version: 1
runtime: python
api_version: 1

#default_expiration: "1h"

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: main.py